.TH Man_uel 1 "13 June 2023" "1.0" "uel man page"
.SH NAME
Manuel - A mighty man... 
.SH SYNOPSIS
Man page for my dear friend Manuel
.SH DESCRIPTION
Hello guys, I am Manuel Tomé, I am a tek1 from Epitech, hihi. I love AI and hardware and what can I say, haha, I was in the marine, hihi, and did a lot of thing, I'm kind of Manuel :).
My lore is magnificient !

:.................................................................................:.::::::
:...................................................................................::::::
:...................................................................................::::::
:............................................::::.....................................::::
:........................................:==+*###*==-:................................::::
:....................................:-+##%%%#%######*+-::............................::::
:.................................:=*######%%#####%%####**=::...........................::
:...............................=**####%###**+==--==+**####*+=:.........................::
:.............................:+*###*++==---::::::::::::-=+###*=:........................:
:...........................::=*#*=---:::::::::::::::::::::-+###+-:......................:
:...........................:+#*=::::::::::::::::::::::::::::-+##*-:.....................:
:...........................=#*-:::::::::::::::::::::::::::::::=##*:.....................:
:.........................-*##-::::::::::::::::::::::::::::::::-*##*-....................:
:........................:+##+:::::::::::::::::::::-:::::::::::-*###*:...................:
:........................-*##-==++***+=-::::::::-=+####***+=-::-*####::..................:
:........................-#####**#####*=-::::::-=*#####****##*=-+###%:...................:
:........................=##*=-----=====-:::::--======-----===+=-##%%-:..................:
:........................-*%=----==++++==-:::::-+***++*++===----:+%%#=::.................:
:........................:+#--=+*+#%%#**=-:::::-=*##+%%%#*#*+=-::-%%#*-:.................:
:.........................-+:-++=-+**+==-:::::::-==+++**+==+=--:::*%##*-.................:
:.........................-::::::::-::::::::::::::::----::::::::::=#*+==.................:
:.........................:::::::::::::::::::::::::::::::::::::::::#+*=:.................:
:.........................:::::::::::::::::::::::::::::::::::::::::+-+=..................:
:.........................::::::::::::::::::::::::--:::::::::::::::+-=:..................:
:.........................:::::::::::::-==-==++=::----::::::::::::-*=-...................:
:.........................::::::::::::-=+----=+==-------::::::::::-#=:...................:
:..........................::::::::::-=*#*****##+-:::---:::::::::-=*-....................:
:..........................::::::::-=*##*++*#**##*=--::::::::::---+*:....................:
:.........................:=:::::=+**=------=====+***+=-:::::----=#=....................::
:.........................:+=:::=**+-==+++++++++++=****+=-::---=+##=:...................::
:..........................+*=:-++====-==-========+***+*+----=+*#%*-.................:::::
:..........................=#*=-=-:::----------------=+++===+*##%#::................::::::
:..........................-*#*+=-:::--+******++==----==+++*##%%*-:................:::::::
:...........................-###*=-----=++****+===----==+*#%%%%+:.................::::::::
:...........................:+####*+===-========---=+***##%%%*=:.................:::::::::
:............................:=##%###*+++++++++++++**#%%%%%#=-::................::::::::::
:..............................-+*%%###*******######%%%%%#=--::::..........::::::::::::::-
:.................................-+#%%%%%%%%%%%%%%%%%#++---:::::::::::::::::::::::::::::-
:.................................:::-=*##%%%%%%%%#*+=----::::::::::-+##+-:::::::::::::::-
:................................--::::::-========------:::::::::::::--=#%#*=-:::::::::::-
:.............................:+##-:::::::::-----:::::::::::::::::::--=+%%%%%%##*++=--:::-
:........................:=+*####-:::::::::::::::::::::::::::::::::--=*%%%%%%%%%%%%#####*+
:...................:-=+######%%+:::::::::::::::::::::::::::::::---==#%%%%%%%%%%%%%%%%%#%%
:...............:=+*#########%%#=:::::::::::::::::::::::::::::--===*%%%%%%%%%%%%%%%%%%%%%%
:............-+*######%%%%%%%%%*=:::::::::::::::::::::::::::--===*#%%%%%%%%%%%%%%%%%%%%%%%
.SH OPTIONS
No options, Manuel is really useful by himself !
.SH SEE ALSO
sl(1), axel(1), oneko(1) 
.SH BUGS
Manuel IS NOT A BUG !
.SH AUTHOR
rahul25 (D:)
